---
- hosts: localhost
  vars_files: vars/env.yaml
  gather_facts: yes
  become: true
  tasks: 
    - name: Create a virtual machine from a template
      community.vmware.vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        datacenter: "{{ vcenter_datacenter }}"
        validate_certs: no
        resource_pool: "{{ vm.resource_pool }}"
        folder: /test-msb
        name: "{{ vm.name }}"
        state: poweredon
        template: centos7-2009
        esxi_hostname: "{{ vm.esxi_hostname }}"
        disk: "{{ vm.disk }}"
        hardware:
          memory_mb: 4096
          num_cpus: 2
          num_cpu_cores_per_socket: 1
          scsi: paravirtual
          max_connections: 5
          hotadd_cpu: True
          hotremove_cpu: True
          hotadd_memory: False
          boot_firmware: "efi"
        networks: "{{ vm.networks }}"
        customization:
          dns_servers: 8.8.8.8 
        wait_for_ip_address: true
        wait_for_ip_address_timeout: 600
    #  loop: "{{ vms }}" 
      delegate_to: localhost
      register: deploy