- hosts: all
  tasks:
    - name: stop webserver
      ignore_errors: true
      service:
        name: httpd
        state: stopped
    - name: uninstall httpd
      yum:
        name: "httpd"
        state: absent